version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/app/
permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    mode: 644
    type:
      - directory
hooks:
  BeforeInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: ubuntu