version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/app/
hooks:
  BeforeInstall:
    - location: deploy/start_server
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start_server
      timeout: 300
      runas: ubuntu