version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing project dependencies ..."
      - yarn install
#   build:
#     commands:
#       - echo "Building project ..."
#       - yarn run build
  post_build:
    commands:
      - echo "Build completed on `date`"
