### SIGNUP USER
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "username": "jadoe",
    "email": "jadoe@some.com",
    "password": "janedoe"
}

### LOGIN USER
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "jadoe",
    "password": "janedoe"
}

### LOGOUT USER
GET http://localhost:3000/logout HTTP/1.1

### CREATE TODO ITEM
POST http://localhost:3000/item HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyMSI6eyJfaWQiOiI2MTJhNjcxZDAxODdmZTQyMzkxMTg0OTEiLCJuYW1lIjoiSmFuZSBEb2UiLCJ1c2VybmFtZSI6ImphZG9lIiwiZW1haWwiOiJqYW5lZG9lQHNvbWUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkSTNiZld0QU1mcDNIZmVXYzIudG1OZUguSnJwcDQwc3ZlQldCOG9WZWtHeUhKRWNBbVQwUTYiLCJfX3YiOjB9LCJpYXQiOjE2MzgwOTIyNzUsImV4cCI6MTYzODA5NDA3NX0.Gcw8ddr1KDS2Mm0bi1ANOGnPOB376NIathvzma9wx4I
Content-Type: application/json

{
    "details": "Lorem dipsum id error incidunt",
    "completed": false
}

### GET ALL TODO ITEM
GET http://localhost:3000/item HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyMSI6eyJfaWQiOiI2MTJhNjcxZDAxODdmZTQyMzkxMTg0OTEiLCJuYW1lIjoiSmFuZSBEb2UiLCJ1c2VybmFtZSI6ImphZG9lIiwiZW1haWwiOiJqYW5lZG9lQHNvbWUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkSTNiZld0QU1mcDNIZmVXYzIudG1OZUguSnJwcDQwc3ZlQldCOG9WZWtHeUhKRWNBbVQwUTYiLCJfX3YiOjB9LCJpYXQiOjE2MzgwOTIyNzUsImV4cCI6MTYzODA5NDA3NX0.Gcw8ddr1KDS2Mm0bi1ANOGnPOB376NIathvzma9wx4I

### GET SINGLE TODO ITEM
GET http://localhost:3000/item/61a34e18fbde6a40e8540fac HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyMSI6eyJfaWQiOiI2MTJhNjcxZDAxODdmZTQyMzkxMTg0OTEiLCJuYW1lIjoiSmFuZSBEb2UiLCJ1c2VybmFtZSI6ImphZG9lIiwiZW1haWwiOiJqYW5lZG9lQHNvbWUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkSTNiZld0QU1mcDNIZmVXYzIudG1OZUguSnJwcDQwc3ZlQldCOG9WZWtHeUhKRWNBbVQwUTYiLCJfX3YiOjB9LCJpYXQiOjE2MzgwOTIyNzUsImV4cCI6MTYzODA5NDA3NX0.Gcw8ddr1KDS2Mm0bi1ANOGnPOB376NIathvzma9wx4I

### UPDATE TODO ITEM
PUT http://localhost:3000/item/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyMSI6eyJfaWQiOiI2MTJhNjcxZDAxODdmZTQyMzkxMTg0OTEiLCJuYW1lIjoiSmFuZSBEb2UiLCJ1c2VybmFtZSI6ImphZG9lIiwiZW1haWwiOiJqYW5lZG9lQHNvbWUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkSTNiZld0QU1mcDNIZmVXYzIudG1OZUguSnJwcDQwc3ZlQldCOG9WZWtHeUhKRWNBbVQwUTYiLCJfX3YiOjB9LCJpYXQiOjE2MzgwOTIyNzUsImV4cCI6MTYzODA5NDA3NX0.Gcw8ddr1KDS2Mm0bi1ANOGnPOB376NIathvzma9wx4I
Content-Type: application/json

{
    "details": "Lorem dipsum id error"
}

### DELETE TODO ITEM
DELETE http://localhost:3000/item/61a34e18fbde6a40e8540fad HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyMSI6eyJfaWQiOiI2MTJhNjcxZDAxODdmZTQyMzkxMTg0OTEiLCJuYW1lIjoiSmFuZSBEb2UiLCJ1c2VybmFtZSI6ImphZG9lIiwiZW1haWwiOiJqYW5lZG9lQHNvbWUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkSTNiZld0QU1mcDNIZmVXYzIudG1OZUguSnJwcDQwc3ZlQldCOG9WZWtHeUhKRWNBbVQwUTYiLCJfX3YiOjB9LCJpYXQiOjE2MzgwOTIyNzUsImV4cCI6MTYzODA5NDA3NX0.Gcw8ddr1KDS2Mm0bi1ANOGnPOB376NIathvzma9wx4I

